export const PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  ABOUT: "/about",
  BLOG: "/blog",
  FAQ: "/faq",
  CONTACT: "/contact",
  NOTFOUNT: "/notfound",
  SERVICES: "/services",
  OTPPAGE: "/otppage",
  PASSWORDPAGE: "/passwordpage",
  RIDESHARE: "/busticket",
  BUSTICKET: "/rideshare",
};
